config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
 resources :users
 resources :books do
   resources :book_comments
   resource :favorites
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end



end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController


 def create
   @book = Book.find(params[:book_id])
   @book_comment = current_user.book_comments.new(book_comment_params)
   @book_comment.book_id = @book.id
   @book_comment.save
   redirect_to book_path(@book.id)
 end

 def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_to book_path(params[:book_id])
 end



 private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end







end

app/controllers/books_controller.rb
class BooksController < ApplicationController



  def create
    @book = Book.new(book_params)
    @user = current_user
    @book.user_id = current_user.id
    if @book.save
     flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    @users = User.all
    @book_comment = BookComment.new
    @book_comment_comment = @book.book_comments
  end

  def show
     @book = Book.find(params[:id])
     @user = @book.user
     @newbook = Book.new
     @book_comment = BookComment.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
     redirect_to books_path
    end
  end

  def update
     @book = Book.find(params[:id])
     if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
     else
      render :edit


     end
  end


 private

   def book_params
    params.require(:book).permit(:body, :title)
   end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)

  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    url = request.referer
    redirect_to url
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find(params[:id])
     @books = Book.where(user_id: @user.id)
     @book = Book.new
     @book_comment = BookComment.new

  end

  def index
     @users = User.all
     @book = Book.new
     @books = Book.all
     @user = current_user
  end

  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
      redirect_to user_path(current_user), notice: 'Book was successfully updated.'
     else
      render :edit
     end
  end

  def edit
     @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

 private

   def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
   end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  <h1>User info</h1>
  <table class="table">
    <thead>
      <tr>
        <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">name</th>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <th scope="row">introduction</th>
        <td><%= user.introduction %></td>
      </tr>
    </tbody>
  </table>




  <div class="row">
    <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
        <span class="fas fa-user-cog" aria-hidden="true"></span>
     　 <% end %>

  </div>
  <div class="row">
         <h1>New book</h1>
      <%= form_with model: book, local:true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book', class:"btn btn-success"%>
      <% end %>
    </div>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h1>Editing Book</h1>
      	<%= form_with model:@book, local:true do |f| %>
      	<%= render 'layouts/error_messages', model: f.object %>
          <h5>Title</h5>
           <%= f.text_field :title %>
          <h5>Opinion</h5>
           <%= f.text_area :body %>
           <%= f.submit 'Update Book', class:"btn btn-success" %>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %>
        <%= link_to "Back", books_path %>
    </div>
   </div>
  </div>
</main>

app/views/books/index.html.erb
<div  class="row">
<div class="col-md-3">
  <%= render 'books/list', book: @book, user: @user  %>
</div>



 <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
    <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
            <% end %>
            </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>
            <% if book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart"><%= book.favorites.count %>いいね </i>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="fas fa-heart"><%= book.favorites.count %>いいね </i>
                <% end %>
              </p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/books/show.html.erb
<div class="row">
<div class="col-md-3">
  <%= render 'books/list', book: @newbook, user: @user  %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
        <tr>
        <td>
          <%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
          <% end %>
          </td>
          <td><%= link_to @user.name, user_path(@user.id) %></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success edit_book_29457" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn btn-sm btn-danger destroy_book_29457" %></td>
　　　　　<% end %>
　　　　　<td>
　　　　　  <%=   %>
　　　　　  <% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class="fas fa-heart"><%= @book.favorites.count %></i>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="fas fa-heart"><%= @book.favorites.count %>いいね</i>
                <% end %>
              </p>
            <% end %>
　　　　　</td>
        </tr>
    </tbody>
  </table>

    <div>
     <p>コメント件数：<%= @book.book_comments.count %></p>
       <% @book.book_comments.each do |book_comment| %>
         <p><%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></p>
            <%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
            <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <div>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn btn-sm btn-danger destroy_book_29457" %>
              </div>
            <% end %>
       <% end %>
    </div>
    <div>
    <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
    <%= f.text_area :comment, size: "60x5" %>
    <%= f.submit '送信', class:"btn btn-success"%>
  　<% end %>
   </div>

</div>
</div>

app/views/homes/about.html.erb
        <p id="notice"></p>
        <div class="container">
        <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path,class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
         <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <h4>errors</h4>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: #{key}) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li><%= link_to "Home", user_path(current_user), class:"fas fa-home nav-link text-light" %></li>
              <li><%= link_to "Users", users_path, class:"fas fa-users nav-link text-light" %></li>
              <li><%= link_to "Books", books_path, class:"fas fa-book-open nav-link text-light" %></li>
              <li><%= link_to "logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>
               <% else%>
               <li>
                <%= link_to "Home", root_path, class:"fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to "About", home_about_path, class:"fas fa-link nav-link text-light" %>
              </li>
              <li>
                <%= link_to "sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
              </li>
               <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
          <%= message %>
           </div>
          <% end %>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>


  </body>
</html>

app/views/users/edit.html.erb
 <main>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>User info</h2>
            <%= form_with model: @user, local:true do |f| %>
             <h6>Name<h6>
             <%= f.text_field :name  %>
             <h6>Image<h6>
             <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
             <h6>Introduction<h6>
             <%= f.text_area :introduction %>
             <%= f.submit 'Update User', class:"btn btn-secondary"%>
            <% end %>
        </div>
      </div>
    </div>
 </main>

app/views/users/index.html.erb
<div class="row">
<div class="col-md-3">
  <p id="notice"><%= notice %></p>
  <%= render 'books/list', book: @book, user: @user  %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td> <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id)%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
<div class="col-md-3">
  <%= render 'books/list', book: @book, user: @user  %>
</div>

    <div class="col-md-8 offset-md-1">
         <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          　<tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                    <% end %>
                  </td>
                  <td> <%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                  <td>コメント件数：<%= book.book_comments.count %></td>
                  <td>
                        <% if book.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorites_path(book), method: :delete do %>
                        <i class="fas fa-heart"><%= book.favorites.count %>いいね </i>
                      <% end %>
                    </p>
                    <% else %>
                    <p>
                      <%= link_to book_favorites_path(book), method: :post do %>
                        <i class="fas fa-heart"><%= book.favorites.count %>いいね </i>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                </tr>
              <% end %>
            </tbody>
          </table>
    </div>
    </div